# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('times', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('promotion', models.CharField(blank=True, max_length=50, null=True)),
                ('published', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'db_table': 'course_open',
                'verbose_name_plural': 'CourseOpen',
            },
        ),
    ]
