# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180109_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'course_option',
                'verbose_name_plural': 'CourseOption',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='app.Teacher'),
        ),
        migrations.AddField(
            model_name='courseoption',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
