# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courseopen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.EmailField(blank=True, max_length=100, null=True)),
                ('persons', models.IntegerField(default=0)),
                ('booking_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'db_table': 'course_booking',
                'verbose_name_plural': 'CourseBooking',
            },
        ),
        migrations.CreateModel(
            name='CourseRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.EmailField(blank=True, max_length=100, null=True)),
                ('persons', models.IntegerField(default=0)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('paid_via', models.CharField(blank=True, max_length=50, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('course_open', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseOpen')),
            ],
            options={
                'db_table': 'course_register',
                'verbose_name_plural': 'CourseRegister',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.EmailField(blank=True, max_length=100, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'db_table': 'quotation',
                'verbose_name_plural': 'Quotation',
            },
        ),
    ]
