# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_quotation_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebooking',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseregister',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
