# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180112_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='company',
            field=models.CharField(default=datetime.datetime(2018, 1, 12, 15, 28, 47, 496000), max_length=100),
            preserve_default=False,
        ),
    ]
