# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='teacher',
        ),
        migrations.AddField(
            model_name='video',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='app.Teacher'),
        ),
    ]
