# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_auto_20180112_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoregister',
            old_name='register_date',
            new_name='reg_date',
        ),
        migrations.RemoveField(
            model_name='videoregister',
            name='member',
        ),
        migrations.AddField(
            model_name='videoregister',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoregister',
            name='name',
            field=models.CharField(default=datetime.datetime(2018, 1, 12, 11, 27, 41, 852000), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoregister',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
