# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 21:36
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
