# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 13:33
from __future__ import unicode_literals

import book.models
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('preview', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[(b'B', b'Both'), (b'E', b'e-Book'), (b'P', b'Paperback')], max_length=1)),
                ('pages', models.IntegerField(default=0)),
                ('years', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('price_ebook', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('example', models.FileField(blank=True, null=True, upload_to=book.models.get_book_exam_file)),
                ('image', models.FileField(blank=True, null=True, upload_to=book.models.get_book_file)),
                ('published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Teacher')),
            ],
            options={
                'db_table': 'book',
                'verbose_name_plural': 'Book',
            },
        ),
        migrations.CreateModel(
            name='BookOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
            ],
            options={
                'db_table': 'book_option',
                'verbose_name_plural': 'BookOption',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('reg_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('paid_via', models.CharField(blank=True, max_length=50, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
            ],
            options={
                'ordering': ['reg_date'],
                'db_table': 'book_register',
                'verbose_name_plural': 'Register',
            },
        ),
    ]
