# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
