# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'book_option',
                'verbose_name_plural': 'BookOption',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='option',
        ),
        migrations.AddField(
            model_name='book',
            name='price_ebook',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='bookoption',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
    ]
