# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180111_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='register',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='register',
            name='unit',
            field=models.IntegerField(default=0),
        ),
    ]
